Repository Hochfrequenz/entscheidungsbaumdiagramme, pull requests merged in 2024-11, with the labels that each got.

#83 build: Switch to svelte's azure-swa adapter
  .github/workflows/azure-static-web-apps-purple-pebble-028724203.yml
  .github/workflows/azure-static-web-apps-white-water-047c71203.yml
  package-lock.json
  package.json
  src/app.d.ts
  src/server/ebd-loader.ts
  src/server/format-version-loader.ts
  svelte.config.js
Labels: build

#84 revert: "build: Switch to svelte's azure-swa adapter"
  .github/workflows/azure-static-web-apps-purple-pebble-028724203.yml
  .github/workflows/azure-static-web-apps-white-water-047c71203.yml
  package-lock.json
  package.json
  src/app.d.ts
  src/server/ebd-loader.ts
  src/server/format-version-loader.ts
  svelte.config.js
Labels: revert

#86 build: Prerender dynamic routes to provide all entries during SSG
  .github/workflows/azure-static-web-apps-purple-pebble-028724203.yml
  .github/workflows/azure-static-web-apps-white-water-047c71203.yml
  .github/workflows/building.yml
  .github/workflows/testing.yml
  src/lib/features/ebd-form-header.svelte
  src/lib/features/export-button.svelte
  src/routes/+layout.ts
  src/routes/ebd/+page.svelte
  src/routes/ebd/[...ebd]/+page.server.ts
  src/routes/ebd/[...ebd]/+page.svelte
  src/server/ebd-loader.ts
  src/server/format-version-loader.ts
  src/server/prerender-entries.ts
Labels: build

#96 chore: Update submodule path for prerendering
  README.md
  package.json
  src/server/prerender-entries.ts
Labels: chore

#97 feat: Change EBD select to input to facilitate filtering
  eslint.config.js
  src/lib/features/ebd-select.svelte
Labels: feature

#99 refactor: Reorganize lib and components
  src/lib/components/features/ebd-form-header.svelte
  src/lib/components/features/ebd-select.svelte
  src/lib/components/features/export-button.svelte
  src/lib/components/features/format-version-select.svelte
  src/lib/components/index.ts
  src/lib/components/shared/footer.svelte
  src/lib/components/shared/header.svelte
  src/lib/components/shared/icon-login.svelte
  src/lib/components/shared/icon-logo.svelte
  src/lib/components/shared/icon-logout.svelte
  src/lib/components/shared/login-button.svelte
  src/lib/components/shared/tools-banner.svelte
  src/lib/index.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/ebd/+page.svelte
  src/routes/ebd/[...ebd]/+layout.svelte
Labels: refactor

#100 refactor: Configure path aliases for more consistent imports
  src/auth/authService.ts
  src/lib/components/index.ts
  src/lib/components/shared/login-button.svelte
  src/routes/+layout.server.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/ebd/+layout.svelte
  src/routes/ebd/+page.server.ts
  src/routes/ebd/[...ebd]/+layout.svelte
  src/routes/ebd/[...ebd]/+page.server.ts
  src/server/prerender-entries.ts
  tsconfig.json
  vite.config.ts
Labels: refactor

#104 feat: Add custom fallback to handle 404 errors on azure
  src/lib/components/index.ts
  src/lib/components/shared/footer.svelte
  src/lib/components/shared/icon-back.svelte
  src/lib/components/shared/icon-heart.svelte
  src/lib/components/shared/icon-plant.svelte
  src/lib/components/shared/landingpage-button.svelte
  src/routes/+error.svelte
  src/routes/ebd/[...ebd]/+page.server.ts
  staticwebapp.config.json
Labels: feature

#105 feat: Add arrow buttons for faster EBD navigation
  eslint.config.js
  package-lock.json
  package.json
  src/lib/components/features/ebd-form-header.svelte
  src/lib/components/features/ebd-input.svelte
  src/lib/components/features/ebd-navigation.svelte
  src/lib/components/features/format-version-select.svelte
  src/lib/components/index.ts
  src/lib/components/shared/icon-arrow.svelte
  src/routes/ebd/+page.svelte
Labels: feature

#115 refactor: Replace deprecated `createEventDispatcher` with props callbacks
  src/lib/components/features/ebd-form-header.svelte
  src/lib/components/features/ebd-input.svelte
  src/lib/components/features/format-version-select.svelte
  src/routes/ebd/+page.svelte
Labels: refactor

#119 chore(build): use `precompress: true`
  svelte.config.js
Labels: chore

#133 chore: apply corporate design
  src/lib/components/features/ebd-form-header.svelte
  src/lib/components/features/ebd-input.svelte
  src/lib/components/features/filter-role-select.svelte
  src/lib/components/features/format-version-select.svelte
  src/lib/components/shared/footer.svelte
  src/lib/components/shared/header.svelte
  src/lib/components/shared/landingpage-button.svelte
  src/routes/+page.svelte
  tailwind.config.js
Labels: chore
