Repository Hochfrequenz/entscheidungsbaumdiagramme, pull requests merged in 2025-02, with the labels that each got.

#217 feat: add filter elements to separate panel below header
  src/lib/components/features/ebd-input.svelte
  src/lib/components/features/filter-chapter-select.svelte
  src/lib/components/features/filter-panel.svelte
  src/lib/components/features/filter-role-select.svelte
  src/lib/components/features/filter-section-input.svelte
  src/lib/components/features/format-version-select.svelte
  src/lib/components/features/svg-container.svelte
  src/lib/components/index.ts
  src/lib/components/shared/header.svelte
  src/lib/components/shared/icon-filter-close.svelte
  src/lib/components/shared/icon-filter-open.svelte
Labels: feature

#220 chore: disable download button while on cooldown
  src/lib/components/features/export-button.svelte
Labels: chore

#223 fix: invert EBD navigation arrow behavior
  src/lib/components/features/ebd-navigation.svelte
Labels: fix

#250 fix(ui): replace HF symbol in bottom left corner with HF logo + text
  src/lib/components/index.ts
  src/lib/components/shared/footer.svelte
  src/lib/components/shared/icon-logo-with-text.svelte
Labels: fix

#259 fix: change landing page card rule color from `secondary` to `primary`
  .prettierignore
  src/routes/+page.svelte
Labels: fix

#261 fix: set height of FV <select> and EBD <input> to `50 px`
  src/lib/components/features/ebd-input.svelte
  src/lib/components/features/format-version-select.svelte
Labels: fix

#262 fix: separate landing page title and subtitle
  src/routes/+page.svelte
Labels: fix

#263 fix: shorten description on landing page
  src/lib/components/shared/footer.svelte
  src/routes/+page.svelte
Labels: fix

#268 refactor: replace nav arrows with custom icon
  src/lib/components/features/ebd-navigation.svelte
  src/lib/components/shared/header.svelte
  src/lib/components/shared/icon-arrow.svelte
Labels: refactor

#269 chore: replace filter icon and add button background
  src/lib/components/features/filter-panel.svelte
  src/lib/components/index.ts
  src/lib/components/shared/header.svelte
  src/lib/components/shared/icon-filter-close.svelte
  src/lib/components/shared/icon-filter-open.svelte
  src/lib/components/shared/icon-filter.svelte
Labels: chore

#270 fix: use equal padding of `gap-4` between header elements
  src/lib/components/shared/header.svelte
Labels: fix

#282 fix: use corporate design color for AHB button
  src/lib/components/shared/footer-tools.svelte
  tailwind.config.js
Labels: fix

#288 chore: replace "open" icon with HF login icon
  src/lib/components/index.ts
  src/lib/components/shared/icon-login.svelte
  src/lib/components/shared/icon-square-arrow.svelte
  src/routes/+page.svelte
Labels: chore

#290 chore: replace download icon with custom HF download icon
  src/lib/components/shared/icon-download.svelte
Labels: chore

#292 feat: add logout button to header
  src/lib/components/features/export-button.svelte
  src/lib/components/shared/auth-button.svelte
  src/lib/components/shared/icon-logout.svelte
  src/routes/ebd/+page.svelte
Labels: feature

#291 chore: replace heart icon with custom HF heart icon
  src/lib/components/shared/icon-heart.svelte
Labels: chore

#293 build: remove `lucide` icon library dependency
  package-lock.json
  package.json
  src/lib/components/index.ts
  src/lib/components/shared/icon-back.svelte
Labels: build

#294 feat: auto select format version by default depending on current date
  src/lib/components/features/format-version-select.svelte
  src/lib/components/shared/icon-download.svelte
  src/lib/components/shared/icon-heart.svelte
  src/lib/components/shared/icon-login.svelte
  src/lib/components/shared/icon-plant.svelte
Labels: feature
